---
title: "JSC370 Final Project"
subtitle: "A research into performance of tennis players in ATP"
author: "You Peng"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

<br>

Welcome to my JSC370 Final Project website. The project involves a research into factors affecting the performance of tennis players in Association of Tennis Professionals (ATP). I will use various statistical approaches and machine learning models aiming to provide some insights into the performance of tennis players based on certain characteristics.

<br>

<br>

# Introduction

Tennis is a popular sport around the world, and one of the worldwide top-tier tennis tours for men is ATP tour organized by the Association of Tennis Professionals. Those professional tennis players who maintained a high ranking in ATP seem to have something in common. There are already research studying the Association between body height and serve speed in elite tennis players. For example, body height of the men explained 27% of the variance of fastest serve in a match (Vaverka & Cernosek, 2013). Serving speed may not directly contribute to a tennis player’s ranking in tournaments, and there could be more potential factors affecting the performance of tennis players. Therefore, we raise our research question as how could some physical factors and experience of a tennis player be used to explain the variation observed in rankings of 639 players participated in 2017 ATP tournaments. Moreover, if given the physical characteristics and experience of a player, can we predict his ranking in a range of 2074 tennis players from ATP? By exploring the relationship between tennis players’ physical characteristics, experience, and their performance, we could help coaches to better recognize if someone could be a good tennis player and inspire tennis players what they can improve on in order to making progress. The goal of this research is to find a model that is not overly complicated, but also having reasonable properties required to make good predictions.

<br>