---
title: "JSC370 Lab 12"
author: "You Peng"
date: "05/04/2022"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

This is my JSC370 Lab12 content, nothing related to the final project.

# Interactive visuals
```{r, warning=F, message=F}
library(dplyr)
library(data.table)
library(tidyverse)
library(dplyr)
library(plotly)
library(DT)
library(knitr)
source("process_COVID_data.R")
head(cv_states_today)
```

```{r plot1, class.source="code-r-small", warning=F, echo=FALSE}

p1_scatter <- cv_states_today %>% 
  plot_ly(x = ~pop_density, y = ~deathsper100k,
          type = 'scatter', mode = 'markers', color = ~state,
          size = ~population, sizes = c(5, 70), marker = list(sizemode='diameter', opacity=0.5),
          hoverinfo = 'text',
          text = ~paste( paste(state, ":", sep=""), paste(" Cases per 100k: ", per100k, sep="") , paste(" Deaths per 100k: ",
                        deathsper100k, sep=""), sep = "<br>")) %>%
  layout(title = "Population-normalized COVID-19 deaths vs. population density",
                  yaxis = list(title = "Deaths per 100k"), xaxis = list(title = "Population Density"),
         hovermode = "compare")

# filter out "District of Columbia"
cv_states_today_scatter <- cv_states_today %>% filter(state!="District of Columbia")

p2_scatter <- cv_states_today_scatter %>% 
  plot_ly(x = ~pop_density, y = ~deathsper100k,
          type = 'scatter', mode = 'markers', color = ~state,
          size = ~population, sizes = c(5, 70), marker = list(sizemode='diameter', opacity=0.5),
          hoverinfo = 'text',
          text = ~paste( paste(state, ":", sep=""), paste(" Cases per 100k: ", per100k, sep="") , paste(" Deaths per 100k: ",
                        deathsper100k, sep=""), sep = "<br>")) %>%
  layout(title = "Population-normalized COVID-19 deaths vs. population density",
                  yaxis = list(title = "Deaths per 100k"), xaxis = list(title = "Population Density"),
         hovermode = "compare")
```

```{r plot2, class.source="code-r-small", warning=F, echo=FALSE}
p3 <- cv_states_today %>% ggplot(aes(x=pop_density, y=newper100k, color=state, size=population)) + geom_point()

p3_scatter <- ggplotly(p3)

p4 <- cv_states_today %>% filter(state!="District of Columbia") %>% ggplot(aes(x=pop_density, y=newper100k, color=state, size=population)) + geom_point()

p4_scatter <- ggplotly(p4)
```



## A set of plots {.tabset}

Create tabs to display each figure

### First Plot

```{r p1}
p1_scatter
```

### Second Plot

```{r p2}
p2_scatter
```

### Third Plot

```{r p3}
p3_scatter
```

### Fourth Plot

```{r p4}
p4_scatter
```

## {-}

